CREATE TABLE IF NOT EXISTS `shop` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `identifier` VARCHAR(60) NOT NULL,
  `item` VARCHAR(50) NOT NULL,
  `label` VARCHAR(50) NOT NULL,
  `quantity` INT NOT NULL,
  `price` INT NOT NULL,
  `date` TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
